"""
Do not edit this file
Use it exactly as is
All words should always be read at the start,
for a fair comparison
"""

import pathlib
import random
random.seed(55)

# All words, guaranteed :-)
# WORDS_TO_CHECK = 1_000_000_000

# Subset of words
WORDS_TO_CHECK = 100


def load():
    result = [
        word.strip()
        for word in pathlib.Path('../data/words_alpha.txt').read_text().split('\n')
        if word.strip()
    ]
    random.shuffle(result)
    result = result[:WORDS_TO_CHECK]
    return result
